apiVersion: v1
kind: Pod
metadata:
  name: best-server-pod
  labels:
    app: best-server
spec:
  containers:
    - name: best-server
      image: irinaevdokimova11/myapp:latest
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
