apiVersion: v1
kind: Service
metadata:
  name: best-server-service
  labels:
    app: best-server
spec:
  selector:
    app: best-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP